### ISSUE TITLE
Writing D.R.Y Code

### ISSUE THREAD

**Issue by zannain** [aklishy/prj-rev-bwfs-dasmoto#3]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is one of the most well know programming principles. If you find yourself repeating certain styles this is an indication that you may be able to refactor somewhere. 

Several times in your styles you use [`font-family: Helvetica`](https://github.com/aklishy/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L8); since this seems to be the font used in the entire page, two ways of setting a web pages font is using the `body` or `*` selector as so:
  
```css
body {
   font-family: Helvetica;
}
// OR
* {
   font-family: Helvetica;
}
```
